platform :ios, '8.0'

use_frameworks!

target 'KZ_MultiPageViewController_iOS' do
    
    pod 'KZ_Categories'
    pod 'KZ_ReuseScrollView'
    pod 'KZ_Constraints'
    pod 'KZ_MacroDefinition'
    
end
